import Mathlib

/-!
# Moh's P3 curve as a set-theoretic complete intersection

Let `k` be a field of characteristic zero.  The Moh curve is parametrized by

`x = t^6 + t^31`,  `y = t^8`,  `z = t^10`.

The four displayed polynomials below generate its prime ideal `P`.  The two
explicit witnesses `H1`, `H2` generate `Q`.  The two advertised theorems say,
both in `k[x,y,z]` and in `k[[x,y,z]]`, that

`ker rho = P`,  `radical Q = P`,  `height P = 2`,  and `arithRank P = 2`.

Thus the curve is cut out set-theoretically by exactly two equations.  The
formal-power-series statement is unconditional: it has no hidden generation,
closedness, Noetherianity, or completion hypothesis beyond `[Field k]` and
`[CharZero k]`.
-/

noncomputable section

namespace MohP3

/-- The arithmetic rank of `I`: the least size of a finite set whose generated
ideal has the same radical as `I`. -/
noncomputable def arithRank {A : Type*} [CommRing A] (I : Ideal A) : ℕ∞ :=
  ⨅ s ∈ {s : Finset A | (Ideal.span (s : Set A)).radical = I.radical}, (s.card : ℕ∞)

namespace Gen

variable {A : Type*} [CommRing A]

def f1 (x y z : A) : A :=
  x^4 - x^2*y^4*z^3 - 2*x*y^6*z^2 - 4*x*y*z - 3*y^3*z^5 + 3*y^3

def f2 (x y z : A) : A :=
  x^3*y - x*y^5*z^3 - 3*x*z^2 - 2*y^7*z^2 + 2*y^2*z

def f3 (x y z : A) : A :=
  2*x^3*z - 3*x^2*y^2 - 2*x*y^4*z^4 - y^6*z^3 + y*z^2

def f4 (x y z : A) : A :=
  x^2*y*z - 2*x*y^3 - y^5*z^4 + z^3

def ell (x y z : A) : A :=
  64*x^4*y*z^2 - 40*x^3*y^3*z + 72*x*y^2*z^3 - 81*y^4*z^2

def kappa (x y z : A) : A :=
  -40*x^3*y^2*z^2 + 25*x^2*y^4*z + 36*y^3*z^3

/-- The first explicit equation. -/
def H1 (x y z : A) : A :=
  81*f4 x y z - 24*x*f1 x y z + ell x y z*f3 x y z

/-- The second explicit equation. -/
def H2 (x y z : A) : A :=
  -12*y*f1 x y z + 27*x*f2 x y z + kappa x y z*f3 x y z

/-- The four-generated Moh curve ideal. -/
def P (x y z : A) : Ideal A :=
  Ideal.span ({f1 x y z, f2 x y z, f3 x y z, f4 x y z} : Set A)

/-- The ideal generated by the two explicit equations. -/
def Q (x y z : A) : Ideal A :=
  Ideal.span ({H1 x y z, H2 x y z} : Set A)

end Gen

open MvPolynomial

/-- The polynomial ring `k[x,y,z]`. -/
abbrev Rk (k : Type*) [Field k] := MvPolynomial (Fin 3) k

def xk (k : Type*) [Field k] : Rk k := X 0
def yk (k : Type*) [Field k] : Rk k := X 1
def zk (k : Type*) [Field k] : Rk k := X 2

/-- The four-generated curve ideal in `k[x,y,z]`. -/
def Ppoly (k : Type*) [Field k] : Ideal (Rk k) := Gen.P (xk k) (yk k) (zk k)

/-- The two-generated witness ideal in `k[x,y,z]`. -/
def Qpoly (k : Type*) [Field k] : Ideal (Rk k) := Gen.Q (xk k) (yk k) (zk k)

/-- The polynomial parametrization `x ↦ t⁶+t³¹`, `y ↦ t⁸`, `z ↦ t¹⁰`. -/
def rho_k (k : Type*) [Field k] : Rk k →+* Polynomial k :=
  eval₂Hom Polynomial.C ![Polynomial.X ^ 6 + Polynomial.X ^ 31,
    Polynomial.X ^ 8, Polynomial.X ^ 10]

namespace FormalLocal

open MvPowerSeries

/-- The formal power series ring `k[[x,y,z]]`. -/
abbrev Sk (k : Type*) := MvPowerSeries (Fin 3) k

def xs (k : Type*) [Field k] : Sk k := X 0
def ys (k : Type*) [Field k] : Sk k := X 1
def zs (k : Type*) [Field k] : Sk k := X 2

/-- The four-generated curve ideal in `k[[x,y,z]]`. -/
def Pk (k : Type*) [Field k] : Ideal (Sk k) := Gen.P (xs k) (ys k) (zs k)

/-- The two-generated witness ideal in `k[[x,y,z]]`. -/
def Qk (k : Type*) [Field k] : Ideal (Sk k) := Gen.Q (xs k) (ys k) (zs k)

def aa (k : Type*) [Field k] : Fin 3 → PowerSeries k :=
  ![PowerSeries.X^6 + PowerSeries.X^31, PowerSeries.X^8, PowerSeries.X^10]

lemma hasSubst_aa (k : Type*) [Field k] : MvPowerSeries.HasSubst (aa k) := by
  apply MvPowerSeries.hasSubst_of_constantCoeff_zero
  intro s
  have hX : MvPowerSeries.constantCoeff (PowerSeries.X : PowerSeries k) = 0 :=
    PowerSeries.constantCoeff_X
  fin_cases s <;> simp [aa, hX]

/-- The formal parametrization `k[[x,y,z]] → k[[t]]`. -/
def psi (k : Type*) [Field k] : Sk k →ₐ[k] PowerSeries k :=
  MvPowerSeries.substAlgHom (hasSubst_aa k)

end FormalLocal

namespace Palomar

/-- Globally, the Moh P3 prime is the radical of the two-generated ideal and
has height and arithmetic rank two. -/
theorem global_setTheoretic_completeIntersection
    (k : Type*) [Field k] [CharZero k] :
    RingHom.ker (rho_k k) = Ppoly k ∧
    (Qpoly k).radical = Ppoly k ∧
    (Ppoly k).height = 2 ∧
    arithRank (Ppoly k) = 2 := by
  sorry

/-- After completion, the formal Moh P3 prime is still the radical of the same
two equations and has height and arithmetic rank two. -/
theorem formalLocal_setTheoretic_completeIntersection
    (k : Type*) [Field k] [CharZero k] :
    RingHom.ker (FormalLocal.psi k) = FormalLocal.Pk k ∧
    (FormalLocal.Qk k).radical = FormalLocal.Pk k ∧
    (FormalLocal.Pk k).height = 2 ∧
    arithRank (FormalLocal.Pk k) = 2 := by
  sorry

end Palomar
end MohP3
