import Mathlib

/-!
# Moh P3: definitions

The polynomial ring `R = ℚ[x,y,z]`, the four generators `f1,…,f4` of the curve
ideal `P`, the two witnesses `H1, H2` spanning `Q`, and the monomial-type
parametrization `rho : R →+* ℚ[t]`, `x ↦ t^6 + t^31`, `y ↦ t^8`, `z ↦ t^10`.

All data is transcribed from `witnesses.txt` / `identities.txt`.
-/

noncomputable section

open MvPolynomial

namespace MohP3

/-- The ambient ring `ℚ[x,y,z]`. -/
abbrev R := MvPolynomial (Fin 3) ℚ

def x : R := X 0
def y : R := X 1
def z : R := X 2

def f1 : R :=
  x^4 - x^2*y^4*z^3 - 2*x*y^6*z^2 - 4*x*y*z - 3*y^3*z^5 + 3*y^3

def f2 : R :=
  x^3*y - x*y^5*z^3 - 3*x*z^2 - 2*y^7*z^2 + 2*y^2*z

def f3 : R :=
  2*x^3*z - 3*x^2*y^2 - 2*x*y^4*z^4 - y^6*z^3 + y*z^2

def f4 : R :=
  x^2*y*z - 2*x*y^3 - y^5*z^4 + z^3

def ell : R :=
  64*x^4*y*z^2 - 40*x^3*y^3*z + 72*x*y^2*z^3 - 81*y^4*z^2

def kappa : R :=
  -40*x^3*y^2*z^2 + 25*x^2*y^4*z + 36*y^3*z^3

def H1 : R := 81*f4 - 24*x*f1 + ell*f3
def H2 : R := -12*y*f1 + 27*x*f2 + kappa*f3

/-- The curve ideal, generated by the four Gonzalez--Planas-Vilanova polynomials. -/
def P : Ideal R := Ideal.span ({f1, f2, f3, f4} : Set R)

/-- The ideal generated by the two explicit witnesses. -/
def Q : Ideal R := Ideal.span ({H1, H2} : Set R)

abbrev T := Polynomial ℚ

/-- The parametrization `x ↦ t^6+t^31`, `y ↦ t^8`, `z ↦ t^10`. -/
def rho : R →+* T :=
  eval₂Hom Polynomial.C ![
    Polynomial.X^6 + Polynomial.X^31,
    Polynomial.X^8,
    Polynomial.X^10]

@[simp] lemma rho_C (a : ℚ) : rho (C a) = Polynomial.C a := by
  simp [rho]

@[simp] lemma rho_x : rho x = Polynomial.X^6 + Polynomial.X^31 := by
  simp [rho, x]

@[simp] lemma rho_y : rho y = Polynomial.X^8 := by
  simp [rho, y]

@[simp] lemma rho_z : rho z = Polynomial.X^10 := by
  simp [rho, z]

lemma f1_mem : f1 ∈ P := Ideal.subset_span (by simp)
lemma f2_mem : f2 ∈ P := Ideal.subset_span (by simp)
lemma f3_mem : f3 ∈ P := Ideal.subset_span (by simp)
lemma f4_mem : f4 ∈ P := Ideal.subset_span (by simp)

/-- Membership test for `P` from an explicit representation. -/
lemma mem_P_of_eq {g c1 c2 c3 c4 : R}
    (h : g = c1 * f1 + c2 * f2 + c3 * f3 + c4 * f4) : g ∈ P := by
  rw [h]
  exact P.add_mem (P.add_mem (P.add_mem
    (Ideal.mul_mem_left _ _ f1_mem) (Ideal.mul_mem_left _ _ f2_mem))
    (Ideal.mul_mem_left _ _ f3_mem)) (Ideal.mul_mem_left _ _ f4_mem)

lemma H1_mem : H1 ∈ Q := Ideal.subset_span (by simp)
lemma H2_mem : H2 ∈ Q := Ideal.subset_span (by simp)

/-- A nonzero natural number is a unit of `ℚ`, hence may be cancelled from an
ideal membership. -/
lemma mem_of_nsmul_mem {I : Ideal R} {n : ℕ} (hn : n ≠ 0) {g : R}
    (h : (n : R) * g ∈ I) : g ∈ I := by
  have hq : ((n : ℚ)) ≠ 0 := Nat.cast_ne_zero.mpr hn
  have h2 := Ideal.mul_mem_left I (C ((n : ℚ))⁻¹) h
  rwa [← mul_assoc, show ((n : R)) = C ((n : ℚ)) by simp, ← C_mul,
    inv_mul_cancel₀ hq, C_1, one_mul] at h2

/-- Membership test for `Q` from an explicit representation. -/
lemma mem_Q_of_eq {g a b : R} (h : g = a * H1 + b * H2) : g ∈ Q := by
  rw [h]
  exact Q.add_mem (Ideal.mul_mem_left _ _ H1_mem) (Ideal.mul_mem_left _ _ H2_mem)

end MohP3
