import MohP3.Generic

/-!
# Moh P3: the formal-local statement over `k[[x,y,z]]`

Let `k` be a field of characteristic zero, `Sk = k[[x,y,z]]`, and let

    psi : k[[x,y,z]] → k[[t]],  x ↦ t^6 + t^31,  y ↦ t^8,  z ↦ t^10

be the substitution morphism.  Write `Pk = (f1,f2,f3,f4)` and `Qk = (H1,H2)`
for the two ideals of `Sk` generated by the *same* explicit polynomials as in
the global situation (all their coefficients are integers, so they make sense
over any commutative ring; see `MohP3.Generic`).

This file proves, unconditionally:

* `Qk ≤ Pk` and `Pk ^ 2 ≤ Qk` (the certificate is characteristic-free);
* `(Qk).radical = (Pk).radical`;
* `Pk ≤ RingHom.ker psi`, and `RingHom.ker psi` is prime;
* hence `(Qk).radical ≤ RingHom.ker psi`;
* the eight power series `psi (hh i)` are linearly independent over the
  subring `k[[t^8]] = psi (k[[y]])` (`indepS`), the formal-local analogue of
  `MohP3.indep`.

Consequently the *only* missing ingredient for the formal-local theorem

    (Qk).radical = RingHom.ker psi

is the completed module-generation statement `Generation` below, the
power-series analogue of `MohP3.good_all`; see the section "The missing
lemma".  The theorem is proved from it in `radical_Qk_eq_ker_of_generation`.
-/

noncomputable section

open MvPowerSeries

namespace MohP3.FormalLocal

variable (k : Type*) [Field k] [CharZero k]

/-! ### Setup -/

/-- The formal power series ring `k[[x,y,z]]`. -/
abbrev Sk := MvPowerSeries (Fin 3) k

def xs : Sk k := X 0
def ys : Sk k := X 1
def zs : Sk k := X 2

/-- The curve ideal `(f1,f2,f3,f4)` of `k[[x,y,z]]`. -/
def Pk : Ideal (Sk k) := Gen.P (xs k) (ys k) (zs k)

/-- The ideal `(H1,H2)` of `k[[x,y,z]]`. -/
def Qk : Ideal (Sk k) := Gen.Q (xs k) (ys k) (zs k)

/-- The three power series substituted for `x`, `y`, `z`. -/
def aa : Fin 3 → PowerSeries k :=
  ![PowerSeries.X^6 + PowerSeries.X^31, PowerSeries.X^8, PowerSeries.X^10]

omit [CharZero k] in
lemma hasSubst_aa : MvPowerSeries.HasSubst (aa k) := by
  apply MvPowerSeries.hasSubst_of_constantCoeff_zero
  intro s
  have hX : MvPowerSeries.constantCoeff (PowerSeries.X : PowerSeries k) = 0 :=
    PowerSeries.constantCoeff_X
  fin_cases s <;> simp [aa, hX]

/-- The formal parametrization `k[[x,y,z]] → k[[t]]`. -/
def psi : Sk k →ₐ[k] PowerSeries k := MvPowerSeries.substAlgHom (hasSubst_aa k)

omit [CharZero k] in
@[simp] lemma psi_xs : psi k (xs k) = PowerSeries.X^6 + PowerSeries.X^31 := by
  rw [psi, xs, MvPowerSeries.substAlgHom_X]; simp [aa]

omit [CharZero k] in
@[simp] lemma psi_ys : psi k (ys k) = PowerSeries.X^8 := by
  rw [psi, ys, MvPowerSeries.substAlgHom_X]; simp [aa]

omit [CharZero k] in
@[simp] lemma psi_zs : psi k (zs k) = PowerSeries.X^10 := by
  rw [psi, zs, MvPowerSeries.substAlgHom_X]; simp [aa]

omit [CharZero k] in
lemma hasSubst_ys : PowerSeries.HasSubst (ys k) :=
  PowerSeries.HasSubst.of_constantCoeff_zero (by simp [ys])

/-- The inclusion `k[[y]] ⊆ k[[x,y,z]]`. -/
def iotaS : PowerSeries k →ₐ[k] Sk k := PowerSeries.substAlgHom (hasSubst_ys k)

/-- `k[[t^8]]`: the image of `k[[y]]` under the parametrization. -/
def exp8 : PowerSeries k →ₐ[k] PowerSeries k := PowerSeries.expand 8 (by norm_num)

omit [CharZero k] in
lemma psi_iotaS (q : PowerSeries k) : psi k (iotaS k q) = exp8 k q := by
  rw [exp8, PowerSeries.expand_apply, PowerSeries.subst, psi, iotaS, PowerSeries.substAlgHom,
    MvPowerSeries.coe_substAlgHom, MvPowerSeries.coe_substAlgHom,
    MvPowerSeries.subst_comp_subst_apply (hasSubst_ys k).const (hasSubst_aa k)]
  congr 1
  funext _
  have := psi_ys k
  rwa [psi, MvPowerSeries.coe_substAlgHom] at this

/-! ### The certificate over `k[[x,y,z]]` -/

omit [CharZero k] in
theorem Qk_le_Pk : Qk k ≤ Pk k := Gen.Q_le_P _ _ _

theorem Pk_sq_le_Qk : Pk k ^ 2 ≤ Qk k := Gen.P_sq_le_Q _ _ _

theorem radical_Qk_eq_radical_Pk : (Qk k).radical = (Pk k).radical :=
  Gen.radical_Q_eq_radical_P _ _ _

/-! ### The four generators lie in the kernel -/

omit [CharZero k] in
lemma psi_f1 : psi k (Gen.f1 (xs k) (ys k) (zs k)) = 0 := by
  simp only [Gen.f1, map_add, map_sub, map_mul, map_pow, map_ofNat, psi_xs, psi_ys, psi_zs]
  ring

omit [CharZero k] in
lemma psi_f2 : psi k (Gen.f2 (xs k) (ys k) (zs k)) = 0 := by
  simp only [Gen.f2, map_add, map_sub, map_mul, map_pow, map_ofNat, psi_xs, psi_ys, psi_zs]
  ring

omit [CharZero k] in
lemma psi_f3 : psi k (Gen.f3 (xs k) (ys k) (zs k)) = 0 := by
  simp only [Gen.f3, map_add, map_sub, map_mul, map_pow, map_ofNat, psi_xs, psi_ys, psi_zs]
  ring

omit [CharZero k] in
lemma psi_f4 : psi k (Gen.f4 (xs k) (ys k) (zs k)) = 0 := by
  simp only [Gen.f4, map_add, map_sub, map_mul, map_pow, map_ofNat, psi_xs, psi_ys, psi_zs]
  ring

omit [CharZero k] in
theorem Pk_le_ker : Pk k ≤ RingHom.ker (psi k) := by
  rw [Pk, Gen.P, Ideal.span_le]
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl | rfl | rfl
  · exact RingHom.mem_ker.mpr (psi_f1 k)
  · exact RingHom.mem_ker.mpr (psi_f2 k)
  · exact RingHom.mem_ker.mpr (psi_f3 k)
  · exact RingHom.mem_ker.mpr (psi_f4 k)

omit [CharZero k] in
/-- The kernel of the formal parametrization is prime, since `k[[t]]` is a
domain. -/
theorem ker_psi_isPrime : (RingHom.ker (psi k)).IsPrime := RingHom.ker_isPrime (psi k)

/-- One half of the formal-local statement, unconditionally. -/
theorem radical_Qk_le_ker : (Qk k).radical ≤ RingHom.ker (psi k) := by
  rw [radical_Qk_eq_radical_Pk]
  calc (Pk k).radical ≤ (RingHom.ker (psi k)).radical := Ideal.radical_mono (Pk_le_ker k)
    _ = RingHom.ker (psi k) := (ker_psi_isPrime k).radical

/-! ### The eight module generators and their images -/

/-- The eight elements of `k[[x,y,z]]` of `MohP3.Closure`, read in the power
series ring. -/
def hhS : Fin 8 → Sk k :=
  ![1, xs k, zs k, (xs k)^2, xs k * zs k - (ys k)^2, (xs k)^3 - ys k * zs k,
    (zs k)^2 - ys k * (xs k)^2, (xs k)^2 * zs k - (ys k)^2 * xs k - (ys k)^9]

/-- Their images under `psi`, with the trailing monomial displayed. -/
def vvS : Fin 8 → PowerSeries k :=
  ![1,
    PowerSeries.X^6*(1+PowerSeries.X^25),
    PowerSeries.X^10,
    PowerSeries.X^12*(1+2*PowerSeries.X^25+PowerSeries.X^50),
    PowerSeries.X^41,
    PowerSeries.X^43*(3+3*PowerSeries.X^25+PowerSeries.X^50),
    PowerSeries.X^45*(-2-PowerSeries.X^25),
    PowerSeries.X^47]

/-- The trailing degrees `0, 6, 10, 12, 41, 43, 45, 47`; they are pairwise
distinct modulo `8`. -/
def ooS : Fin 8 → ℕ := ![0, 6, 10, 12, 41, 43, 45, 47]

omit [CharZero k] in
lemma psi_hhS (i : Fin 8) : psi k (hhS k i) = vvS k i := by
  fin_cases i <;> simp [hhS, vvS] <;> ring

lemma ooS_mod_inj {i j : Fin 8} (h : ooS i % 8 = ooS j % 8) : i = j := by
  fin_cases i <;> fin_cases j <;> simp_all [ooS]

omit [CharZero k] in
lemma order_X_pow_mul (n : ℕ) (w : PowerSeries k) (hw : PowerSeries.coeff 0 w ≠ 0) :
    ((PowerSeries.X : PowerSeries k)^n * w).order = (n : ℕ∞) := by
  have h0 : w.order = 0 := le_antisymm (by simpa using PowerSeries.order_le 0 hw) (zero_le _)
  rw [PowerSeries.order_mul, PowerSeries.order_X_pow, h0, add_zero]

lemma order_vvS (i : Fin 8) : (vvS k i).order = (ooS i : ℕ∞) := by
  fin_cases i
  · simp [vvS, ooS]
  · simpa [vvS, ooS] using
      order_X_pow_mul k 6 (1 + PowerSeries.X^25) (by simp)
  · simp [vvS, ooS]
  · simpa [vvS, ooS] using
      order_X_pow_mul k 12 (1 + 2*PowerSeries.X^25 + PowerSeries.X^50) (by simp)
  · simp [vvS, ooS]
  · simpa [vvS, ooS] using
      order_X_pow_mul k 43 (3 + 3*PowerSeries.X^25 + PowerSeries.X^50) (by simp [map_ofNat])
  · simpa [vvS, ooS] using
      order_X_pow_mul k 45 (-2 - PowerSeries.X^25) (by simp [map_ofNat])
  · simp [vvS, ooS]

lemma vvS_ne_zero (i : Fin 8) : vvS k i ≠ 0 := by
  intro h
  have h2 := order_vvS k i
  rw [h, PowerSeries.order_eq_top.mpr rfl] at h2
  exact (ENat.coe_ne_top _) h2.symm

omit [CharZero k] in
lemma order_eq_coe {q : PowerSeries k} (hq : q ≠ 0) : q.order = (q.order.toNat : ℕ∞) := by
  rw [ENat.coe_toNat]
  exact (PowerSeries.order_finite_iff_ne_zero.mpr hq).ne

omit [CharZero k] in
lemma order_exp8 {q : PowerSeries k} (hq : q ≠ 0) :
    (exp8 k q).order = ((8 * q.order.toNat : ℕ) : ℕ∞) := by
  rw [exp8, PowerSeries.order_expand, order_eq_coe k hq, ENat.toNat_coe]
  push_cast
  simp

omit [CharZero k] in
lemma exp8_ne_zero {q : PowerSeries k} (hq : q ≠ 0) : exp8 k q ≠ 0 := by
  intro h
  have h2 := order_exp8 k hq
  rw [h, PowerSeries.order_eq_top.mpr rfl] at h2
  exact (ENat.coe_ne_top _) h2.symm

/-- The formal-local analogue of `MohP3.indep`: the eight power series
`psi (hh i)` are linearly independent over `k[[t^8]]`. -/
theorem indepS (p : Fin 8 → PowerSeries k) (hs : ∑ i, exp8 k (p i) * vvS k i = 0) :
    ∀ i, p i = 0 := by
  classical
  by_contra hcon
  push_neg at hcon
  obtain ⟨i0, hi0⟩ := hcon
  set w : Fin 8 → PowerSeries k := fun i => exp8 k (p i) * vvS k i with hw
  set S : Finset (Fin 8) := Finset.univ.filter (fun i => p i ≠ 0) with hSdef
  have hS : S.Nonempty := ⟨i0, by simp [hSdef, hi0]⟩
  have hwne : ∀ i ∈ S, w i ≠ 0 := by
    intro i hi
    simp [hSdef] at hi
    exact mul_ne_zero (exp8_ne_zero k hi) (vvS_ne_zero k i)
  have hord : ∀ i ∈ S, (w i).order = ((8 * (p i).order.toNat + ooS i : ℕ) : ℕ∞) := by
    intro i hi
    simp [hSdef] at hi
    rw [hw]
    simp only
    rw [PowerSeries.order_mul, order_exp8 k hi, order_vvS]
    push_cast
    ring
  obtain ⟨m, hmS, hmin⟩ := S.exists_min_image (fun i => (w i).order.toNat) hS
  set d := (w m).order.toNat with hd
  have hmod : ∀ i ∈ S, (w i).order.toNat % 8 = ooS i % 8 := by
    intro i hi
    rw [hord i hi, ENat.toNat_coe]
    omega
  have key : PowerSeries.coeff d (∑ i, w i) = PowerSeries.coeff d (w m) := by
    rw [map_sum, Finset.sum_eq_single m]
    · intro b _ hbm
      by_cases hb : b ∈ S
      · have h1 : d ≤ (w b).order.toNat := hmin b hb
        have h2 : (w b).order.toNat ≠ d :=
          fun he => hbm (ooS_mod_inj (by rw [← hmod b hb, ← hmod m hmS, he]))
        refine PowerSeries.coeff_of_lt_order d ?_
        rw [order_eq_coe k (hwne b hb)]
        exact_mod_cast lt_of_le_of_ne h1 (Ne.symm h2)
      · have hp0 : p b = 0 := by simpa [hSdef] using hb
        simp [hw, hp0]
    · intro hm
      exact absurd (Finset.mem_univ m) hm
  rw [hs] at key
  simp at key
  exact (PowerSeries.coeff_order (hwne m hmS)) key.symm

/-! ### The missing lemma

`Generation k` below is the power-series analogue of `MohP3.good_all`: modulo
`Pk`, the `k[[y]]`-submodule of `k[[x,y,z]]` spanned by the eight elements
`hhS i` is everything.  Over the polynomial ring this is proved in
`MohP3.Kernel` from the sixteen explicit identities of `MohP3.Closure`; over
the power series ring the same identities only give the statement modulo every
power of the maximal ideal, and passing to the limit needs

1. adic completeness / Krull intersection in `k[[x,y,z]]` — equivalently, that
   the ideal `Pk` is closed in the `(x,y,z)`-adic topology; and
2. the fact that `MvPowerSeries (Fin 3) k` is Noetherian.

At the Mathlib revision used here neither is available: there is no
`IsNoetherianRing (MvPowerSeries (Fin n) k)` instance, and no
`IsAdicComplete (IsLocalRing.maximalIdeal A) A` instance for `A` a (multi- or
even single-variable) formal power series ring, so the Weierstrass division
machinery of `Mathlib.RingTheory.PowerSeries.WeierstrassPreparation`, which
requires `[IsAdicComplete I A]`, cannot be applied either.  This is the exact
gap; everything else in the formal-local argument is proved in this file.

(`Generation k` is nevertheless proved unconditionally in `MohP3.Generation`,
by an explicit division algorithm for the weighted filtration, so this route is
not needed.  A Noetherianity instance for `MvPowerSeries (Fin n) k` is supplied
by `MohP3.MvPowerSeriesAux` and used in `MohP3.HeightLocal`.) -/

/-- The completed module-generation statement, i.e. the power-series analogue
of `MohP3.good_all`. -/
def Generation : Prop :=
  ∀ F : Sk k, ∃ p : Fin 8 → PowerSeries k, F - ∑ i, iotaS k (p i) * hhS k i ∈ Pk k

/-- Granting the completed generation statement, the kernel of the formal
parametrization is exactly `Pk`. -/
theorem ker_le_Pk_of_generation (hgen : Generation k) : RingHom.ker (psi k) ≤ Pk k := by
  intro F hF
  obtain ⟨p, hp⟩ := hgen F
  have h1 : (∑ i, iotaS k (p i) * hhS k i) ∈ RingHom.ker (psi k) := by
    simpa using sub_mem hF (Pk_le_ker k hp)
  have h2 : ∑ i, exp8 k (p i) * vvS k i = 0 := by
    have h := RingHom.mem_ker.mp h1
    rw [map_sum] at h
    simpa [map_mul, psi_iotaS, psi_hhS] using h
  have h3 := indepS k p h2
  have hzero : (∑ i, iotaS k (p i) * hhS k i) = 0 :=
    Finset.sum_eq_zero fun i _ => by simp [h3 i]
  rwa [hzero, sub_zero] at hp

/-- Granting the completed generation statement, `ker psi = Pk`. -/
theorem ker_eq_Pk_of_generation (hgen : Generation k) : RingHom.ker (psi k) = Pk k :=
  le_antisymm (ker_le_Pk_of_generation k hgen) (Pk_le_ker k)

/-- **The formal-local corollary**, granting the completed generation
statement: the radical of the ideal generated by the two witnesses is the
kernel of the formal parametrization,
`√((H1,H2) k[[x,y,z]]) = ker (k[[x,y,z]] → k[[t]])`. -/
theorem radical_Qk_eq_ker_of_generation (hgen : Generation k) :
    (Qk k).radical = RingHom.ker (psi k) := by
  refine le_antisymm (radical_Qk_le_ker k) ?_
  rw [ker_eq_Pk_of_generation k hgen, radical_Qk_eq_radical_Pk]
  exact Ideal.le_radical

/-- The same corollary, phrased with the kernel identification as hypothesis. -/
theorem radical_Qk_eq_ker_of_ker_le (hker : RingHom.ker (psi k) ≤ Pk k) :
    (Qk k).radical = RingHom.ker (psi k) := by
  refine le_antisymm (radical_Qk_le_ker k) ?_
  refine hker.trans ?_
  rw [radical_Qk_eq_radical_Pk]
  exact Ideal.le_radical

end MohP3.FormalLocal
