import MohP3.Generic

/-!
# The sixteen closure identities over an arbitrary commutative ring

The eight elements

    hh = (1, x, z, x^2, xz - y^2, x^3 - yz, z^2 - yx^2, x^2 z - y^2 x - y^9)

span, modulo the curve ideal `P = (f1,f2,f3,f4)`, a module over the
subring generated by `y`, and this module is stable under multiplication
by `x` and by `z`.  The precise statements are `key_xA` and `key_zA`
below: they are *exact* identities with integer coefficients, hence valid
over every commutative ring, and they are used both over the polynomial
ring (for the kernel computation) and over the formal power series ring
(for the formal-local generation theorem).

All the data is stored in integer arrays:

* `qxD i j = (c, e)` encodes the entry `c * y ^ e` of the `x`-closure matrix;
* `wxD i j t = (c, a, b, c')` encodes the term `c * x^a * y^b * z^c'` of the
  cofactor of `f j` in the `i`-th `x`-closure identity;

and similarly `qzD`, `wzD` for multiplication by `z`.  Unused array slots
carry the coefficient `0` and a large weight, so that the weight
estimates of `MohP3.Generation` hold for *every* slot.

The weights `sig i` and `tau j` recorded here are the weighted orders of
`hh i` and of `f j` for the weighting `wt x = 6, wt y = 8, wt z = 10`.
-/

noncomputable section

namespace MohP3.Gen

variable {A : Type*} [CommRing A]

/-- The eight module generators. -/
def hh (x y z : A) : Fin 8 → A :=
  ![1, x, z, x ^ 2, x * z - y ^ 2, x ^ 3 - y * z, z ^ 2 - y * x ^ 2,
    x ^ 2 * z - y ^ 2 * x - y ^ 9]

/-- The four generators of the curve ideal, as a vector. -/
def ff (x y z : A) : Fin 4 → A := ![f1 x y z, f2 x y z, f3 x y z, f4 x y z]

/-- The weighted order of `hh i`. -/
def sig : Fin 8 → ℕ := ![0, 6, 10, 12, 16, 18, 20, 22]

/-- The weighted order of `ff j`. -/
def tau : Fin 4 → ℕ := ![24, 26, 28, 30]

def qxD : Fin 8 → Fin 8 → ℤ × ℕ :=
  ![![(0, 100), (18, 0), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100)],
    ![(0, 100), (0, 100), (0, 100), (18, 0), (0, 100), (0, 100), (0, 100), (0, 100)],
    ![(18, 2), (0, 100), (0, 100), (0, 100), (18, 0), (0, 100), (0, 100), (0, 100)],
    ![(0, 100), (0, 100), (18, 1), (0, 100), (0, 100), (18, 0), (0, 100), (0, 100)],
    ![(18, 9), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100), (18, 0)],
    ![(0, 100), (12, 21), (108, 8), (-54, 14), (54, 1), (24, 7), (-42, 13), (-12, 19)],
    ![(0, 100), (3, 15), (0, 100), (-18, 8), (0, 100), (-12, 1), (-15, 7), (-3, 13)],
    ![(0, 100), (9, 9), (0, 100), (0, 100), (0, 100), (0, 100), (-9, 1), (-9, 7)]]

def qzD : Fin 8 → Fin 8 → ℤ × ℕ :=
  ![![(0, 100), (0, 100), (18, 0), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100)],
    ![(18, 2), (0, 100), (0, 100), (0, 100), (18, 0), (0, 100), (0, 100), (0, 100)],
    ![(0, 100), (0, 100), (0, 100), (18, 1), (0, 100), (0, 100), (18, 0), (0, 100)],
    ![(18, 9), (18, 2), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100), (18, 0)],
    ![(0, 100), (3, 15), (0, 100), (-18, 8), (0, 100), (6, 1), (-15, 7), (-3, 13)],
    ![(0, 100), (27, 9), (0, 100), (0, 100), (0, 100), (0, 100), (-27, 1), (-9, 7)],
    ![(-18, 10), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100), (-36, 1)],
    ![(0, 100), (0, 100), (0, 100), (0, 100), (18, 2), (0, 100), (0, 100), (0, 100)]]

def wxD : Fin 8 → Fin 4 → Fin 4 → ℤ × ℕ × ℕ × ℕ :=
  ![![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(-4, 0, 25, 0), (-18, 0, 5, 1), (18, 0, 0, 0), (0, 0, 100, 0)],
      ![(4, 1, 24, 0), (12, 1, 4, 1), (8, 0, 11, 1), (-15, 0, 6, 0)],
      ![(3, 1, 5, 0), (-4, 0, 12, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(12, 0, 23, 1), (12, 0, 18, 0), (54, 0, 3, 2), (0, 0, 100, 0)]],
    ![![(-1, 0, 19, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(1, 1, 18, 0), (2, 0, 5, 1), (-6, 0, 0, 0), (0, 0, 100, 0)],
      ![(-1, 0, 6, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(3, 0, 17, 1), (3, 0, 12, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(-3, 0, 13, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(3, 1, 12, 0), (-6, 0, 4, 2), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(3, 0, 5, 1), (9, 0, 0, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(9, 0, 11, 1), (18, 0, 6, 0), (0, 0, 100, 0), (0, 0, 100, 0)]]]

def wzD : Fin 8 → Fin 4 → Fin 4 → ℤ × ℕ × ℕ × ℕ :=
  ![![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(-1, 0, 19, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(1, 1, 18, 0), (2, 0, 5, 1), (-6, 0, 0, 0), (0, 0, 100, 0)],
      ![(-1, 0, 6, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(3, 0, 17, 1), (3, 0, 12, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(-3, 0, 13, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(3, 1, 12, 0), (-6, 0, 4, 2), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(3, 0, 5, 1), (9, 0, 0, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(9, 0, 11, 1), (18, 0, 6, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(-6, 0, 7, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(6, 1, 6, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(18, 0, 5, 1), (18, 0, 0, 0), (0, 0, 100, 0), (0, 0, 100, 0)]],
    ![![(-6, 0, 6, 1), (6, 0, 1, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(6, 1, 5, 1), (-6, 1, 0, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)],
      ![(18, 0, 4, 2), (0, 0, 100, 0), (0, 0, 100, 0), (0, 0, 100, 0)]]]


/-- Entry `(i,j)` of the `x`-closure matrix. -/
def qxA (y : A) (i j : Fin 8) : A := ((qxD i j).1 : A) * y ^ (qxD i j).2

/-- Entry `(i,j)` of the `z`-closure matrix. -/
def qzA (y : A) (i j : Fin 8) : A := ((qzD i j).1 : A) * y ^ (qzD i j).2

/-- The cofactor of `ff j` in the `i`-th `x`-closure identity. -/
def wxA (x y z : A) (i : Fin 8) (j : Fin 4) : A :=
  ∑ t : Fin 4, ((wxD i j t).1 : A) * x ^ (wxD i j t).2.1 * y ^ (wxD i j t).2.2.1 *
    z ^ (wxD i j t).2.2.2

/-- The cofactor of `ff j` in the `i`-th `z`-closure identity. -/
def wzA (x y z : A) (i : Fin 8) (j : Fin 4) : A :=
  ∑ t : Fin 4, ((wzD i j t).1 : A) * x ^ (wzD i j t).2.1 * y ^ (wzD i j t).2.2.1 *
    z ^ (wzD i j t).2.2.2

variable (x y z : A)

/-- The `x`-closure identity for the generator `hh 0`. -/
theorem key_xA_0 :
    (18 : A) * (x * hh x y z 0) =
      (∑ j, qxA y 0 j * hh x y z j) + ∑ j, wxA x y z 0 j * ff x y z j := by
  simp only [hh, ff, qxA, wxA, qxD, wxD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero, zero_add]
  ring

/-- The `z`-closure identity for the generator `hh 0`. -/
theorem key_zA_0 :
    (18 : A) * (z * hh x y z 0) =
      (∑ j, qzA y 0 j * hh x y z j) + ∑ j, wzA x y z 0 j * ff x y z j := by
  simp only [hh, ff, qzA, wzA, qzD, wzD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero, zero_add]
  ring

/-- The `x`-closure identity for the generator `hh 1`. -/
theorem key_xA_1 :
    (18 : A) * (x * hh x y z 1) =
      (∑ j, qxA y 1 j * hh x y z j) + ∑ j, wxA x y z 1 j * ff x y z j := by
  simp only [hh, ff, qxA, wxA, qxD, wxD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero, zero_add]
  ring

/-- The `z`-closure identity for the generator `hh 1`. -/
theorem key_zA_1 :
    (18 : A) * (z * hh x y z 1) =
      (∑ j, qzA y 1 j * hh x y z j) + ∑ j, wzA x y z 1 j * ff x y z j := by
  simp only [hh, ff, qzA, wzA, qzD, wzD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero]
  ring

/-- The `x`-closure identity for the generator `hh 2`. -/
theorem key_xA_2 :
    (18 : A) * (x * hh x y z 2) =
      (∑ j, qxA y 2 j * hh x y z j) + ∑ j, wxA x y z 2 j * ff x y z j := by
  simp only [hh, ff, qxA, wxA, qxD, wxD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero]
  ring

/-- The `z`-closure identity for the generator `hh 2`. -/
theorem key_zA_2 :
    (18 : A) * (z * hh x y z 2) =
      (∑ j, qzA y 2 j * hh x y z j) + ∑ j, wzA x y z 2 j * ff x y z j := by
  simp only [hh, ff, qzA, wzA, qzD, wzD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero, zero_add]
  ring

/-- The `x`-closure identity for the generator `hh 3`. -/
theorem key_xA_3 :
    (18 : A) * (x * hh x y z 3) =
      (∑ j, qxA y 3 j * hh x y z j) + ∑ j, wxA x y z 3 j * ff x y z j := by
  simp only [hh, ff, qxA, wxA, qxD, wxD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero, zero_add]
  ring

/-- The `z`-closure identity for the generator `hh 3`. -/
theorem key_zA_3 :
    (18 : A) * (z * hh x y z 3) =
      (∑ j, qzA y 3 j * hh x y z j) + ∑ j, wzA x y z 3 j * ff x y z j := by
  simp only [hh, ff, qzA, wzA, qzD, wzD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero]
  ring

/-- The `x`-closure identity for the generator `hh 4`. -/
theorem key_xA_4 :
    (18 : A) * (x * hh x y z 4) =
      (∑ j, qxA y 4 j * hh x y z j) + ∑ j, wxA x y z 4 j * ff x y z j := by
  simp only [hh, ff, qxA, wxA, qxD, wxD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, zero_mul, add_zero]
  ring

/-- The `z`-closure identity for the generator `hh 4`. -/
theorem key_zA_4 :
    (18 : A) * (z * hh x y z 4) =
      (∑ j, qzA y 4 j * hh x y z j) + ∑ j, wzA x y z 4 j * ff x y z j := by
  simp only [hh, ff, qzA, wzA, qzD, wzD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, Int.cast_neg, zero_mul, add_zero, zero_add]
  ring

/-- The `x`-closure identity for the generator `hh 5`. -/
theorem key_xA_5 :
    (18 : A) * (x * hh x y z 5) =
      (∑ j, qxA y 5 j * hh x y z j) + ∑ j, wxA x y z 5 j * ff x y z j := by
  simp only [hh, ff, qxA, wxA, qxD, wxD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, Int.cast_neg, zero_mul, add_zero, zero_add]
  ring

/-- The `z`-closure identity for the generator `hh 5`. -/
theorem key_zA_5 :
    (18 : A) * (z * hh x y z 5) =
      (∑ j, qzA y 5 j * hh x y z j) + ∑ j, wzA x y z 5 j * ff x y z j := by
  simp only [hh, ff, qzA, wzA, qzD, wzD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, Int.cast_neg, zero_mul, add_zero, zero_add]
  ring

/-- The `x`-closure identity for the generator `hh 6`. -/
theorem key_xA_6 :
    (18 : A) * (x * hh x y z 6) =
      (∑ j, qxA y 6 j * hh x y z j) + ∑ j, wxA x y z 6 j * ff x y z j := by
  simp only [hh, ff, qxA, wxA, qxD, wxD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, Int.cast_neg, zero_mul, add_zero, zero_add]
  ring

/-- The `z`-closure identity for the generator `hh 6`. -/
theorem key_zA_6 :
    (18 : A) * (z * hh x y z 6) =
      (∑ j, qzA y 6 j * hh x y z j) + ∑ j, wzA x y z 6 j * ff x y z j := by
  simp only [hh, ff, qzA, wzA, qzD, wzD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, Int.cast_neg, zero_mul, add_zero]
  ring

/-- The `x`-closure identity for the generator `hh 7`. -/
theorem key_xA_7 :
    (18 : A) * (x * hh x y z 7) =
      (∑ j, qxA y 7 j * hh x y z j) + ∑ j, wxA x y z 7 j * ff x y z j := by
  simp only [hh, ff, qxA, wxA, qxD, wxD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, Int.cast_neg, zero_mul, add_zero, zero_add]
  ring

/-- The `z`-closure identity for the generator `hh 7`. -/
theorem key_zA_7 :
    (18 : A) * (z * hh x y z 7) =
      (∑ j, qzA y 7 j * hh x y z j) + ∑ j, wzA x y z 7 j * ff x y z j := by
  simp only [hh, ff, qzA, wzA, qzD, wzD, f1, f2, f3, f4, Fin.sum_univ_eight,
    Fin.sum_univ_four, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
    Int.cast_zero, Int.cast_ofNat, Int.cast_neg, zero_mul, add_zero, zero_add]
  ring



/-- Multiplication by `x` on the eight generators, modulo the curve ideal. -/
theorem key_xA (i : Fin 8) :
    (18 : A) * (x * hh x y z i) =
      (∑ j, qxA y i j * hh x y z j) + ∑ j, wxA x y z i j * ff x y z j := by
  fin_cases i
  exacts [key_xA_0 x y z, key_xA_1 x y z, key_xA_2 x y z, key_xA_3 x y z,
    key_xA_4 x y z, key_xA_5 x y z, key_xA_6 x y z, key_xA_7 x y z]

/-- Multiplication by `z` on the eight generators, modulo the curve ideal. -/
theorem key_zA (i : Fin 8) :
    (18 : A) * (z * hh x y z i) =
      (∑ j, qzA y i j * hh x y z j) + ∑ j, wzA x y z i j * ff x y z j := by
  fin_cases i
  exacts [key_zA_0 x y z, key_zA_1 x y z, key_zA_2 x y z, key_zA_3 x y z,
    key_zA_4 x y z, key_zA_5 x y z, key_zA_6 x y z, key_zA_7 x y z]

/-- The weight estimate for the `x`-closure matrix. -/
theorem qxD_wt (i j : Fin 8) : 6 + sig i ≤ 8 * (qxD i j).2 + sig j := by
  fin_cases i <;> fin_cases j <;> simp [qxD, sig]

/-- The weight estimate for the `z`-closure matrix. -/
theorem qzD_wt (i j : Fin 8) : 10 + sig i ≤ 8 * (qzD i j).2 + sig j := by
  fin_cases i <;> fin_cases j <;> simp [qzD, sig]

/-- The weight estimate for the `x`-closure cofactors. -/
theorem wxD_wt (i : Fin 8) (j : Fin 4) (t : Fin 4) :
    6 + sig i ≤ 6 * (wxD i j t).2.1 + 8 * (wxD i j t).2.2.1 + 10 * (wxD i j t).2.2.2 + tau j := by
  fin_cases i <;> fin_cases j <;> fin_cases t <;> simp [wxD, sig, tau]

/-- The weight estimate for the `z`-closure cofactors. -/
theorem wzD_wt (i : Fin 8) (j : Fin 4) (t : Fin 4) :
    10 + sig i ≤ 6 * (wzD i j t).2.1 + 8 * (wzD i j t).2.2.1 + 10 * (wzD i j t).2.2.2 + tau j := by
  fin_cases i <;> fin_cases j <;> fin_cases t <;> simp [wzD, sig, tau]

end MohP3.Gen
