import Mathlib

/-!
# The Moh P3 certificate over an arbitrary commutative ring

All the polynomial identities of the certificate have integer coefficients, so
they are identities in any commutative ring `A`, for any three elements
`x y z : A`.  This file states and proves them once and for all; the ring
`ℚ[x,y,z]` (file `MohP3.Certificate`) and the formal power series ring
`k[[x,y,z]]` (file `MohP3.FormalLocal`) are then two instantiations.

The only place where a hypothesis on `A` is needed is `P_sq_le_Q`, where the
ten integer scales `d_ij` have to be invertible; we assume `[Algebra ℚ A]`.
-/

noncomputable section

namespace MohP3.Gen

variable {A : Type*} [CommRing A]

def f1 (x y z : A) : A :=
  x^4 - x^2*y^4*z^3 - 2*x*y^6*z^2 - 4*x*y*z - 3*y^3*z^5 + 3*y^3

def f2 (x y z : A) : A :=
  x^3*y - x*y^5*z^3 - 3*x*z^2 - 2*y^7*z^2 + 2*y^2*z

def f3 (x y z : A) : A :=
  2*x^3*z - 3*x^2*y^2 - 2*x*y^4*z^4 - y^6*z^3 + y*z^2

def f4 (x y z : A) : A :=
  x^2*y*z - 2*x*y^3 - y^5*z^4 + z^3

def ell (x y z : A) : A :=
  64*x^4*y*z^2 - 40*x^3*y^3*z + 72*x*y^2*z^3 - 81*y^4*z^2

def kappa (x y z : A) : A :=
  -40*x^3*y^2*z^2 + 25*x^2*y^4*z + 36*y^3*z^3

def H1 (x y z : A) : A := 81*f4 x y z - 24*x*f1 x y z + ell x y z*f3 x y z
def H2 (x y z : A) : A := -12*y*f1 x y z + 27*x*f2 x y z + kappa x y z*f3 x y z

/-- The curve ideal. -/
def P (x y z : A) : Ideal A := Ideal.span ({f1 x y z, f2 x y z, f3 x y z, f4 x y z} : Set A)

/-- The ideal generated by the two witnesses. -/
def Q (x y z : A) : Ideal A := Ideal.span ({H1 x y z, H2 x y z} : Set A)

variable (x y z : A)

lemma f1_mem : f1 x y z ∈ P x y z := Ideal.subset_span (by simp)
lemma f2_mem : f2 x y z ∈ P x y z := Ideal.subset_span (by simp)
lemma f3_mem : f3 x y z ∈ P x y z := Ideal.subset_span (by simp)
lemma f4_mem : f4 x y z ∈ P x y z := Ideal.subset_span (by simp)
lemma H1_mem : H1 x y z ∈ Q x y z := Ideal.subset_span (by simp)
lemma H2_mem : H2 x y z ∈ Q x y z := Ideal.subset_span (by simp)

/-- Membership test for `P` from an explicit representation. -/
lemma mem_P_of_eq {x y z : A} {g c1 c2 c3 c4 : A}
    (h : g = c1 * f1 x y z + c2 * f2 x y z + c3 * f3 x y z + c4 * f4 x y z) : g ∈ P x y z := by
  rw [h]
  exact (P x y z).add_mem ((P x y z).add_mem ((P x y z).add_mem
    (Ideal.mul_mem_left _ _ (f1_mem x y z)) (Ideal.mul_mem_left _ _ (f2_mem x y z)))
    (Ideal.mul_mem_left _ _ (f3_mem x y z))) (Ideal.mul_mem_left _ _ (f4_mem x y z))

/-- Membership test for `Q` from an explicit representation. -/
lemma mem_Q_of_eq {x y z : A} {g a b : A} (h : g = a * H1 x y z + b * H2 x y z) : g ∈ Q x y z := by
  rw [h]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

/-- Over a `ℚ`-algebra a nonzero natural number is invertible, so it may be
cancelled from an ideal membership. -/
lemma mem_of_nsmul_mem [Algebra ℚ A] {I : Ideal A} {n : ℕ} (hn : n ≠ 0) {g : A}
    (h : (n : A) * g ∈ I) : g ∈ I := by
  have hcast : ((n : ℕ) : A) = algebraMap ℚ A (n : ℚ) := by
    simp
  have hunit : IsUnit ((n : ℕ) : A) := by
    rw [hcast]
    exact (isUnit_iff_ne_zero.mpr (Nat.cast_ne_zero.mpr hn)).map (algebraMap ℚ A)
  obtain ⟨u, hu⟩ := hunit
  have := Ideal.mul_mem_left I (↑u⁻¹) h
  rwa [← mul_assoc, ← hu, Units.inv_mul, one_mul] at this

/-- Expanded form of `H1`, as recorded in `witnesses.txt`. -/
theorem H1_expanded : H1 x y z =
    128*x^7*y*z^3 - 272*x^6*y^3*z^2 - 128*x^5*y^5*z^6
    + 120*x^5*y^5*z - 24*x^5 + 16*x^4*y^7*z^5
    + 208*x^4*y^2*z^4 + 40*x^3*y^9*z^4 - 394*x^3*y^4*z^3
    - 144*x^2*y^6*z^7 + 291*x^2*y^6*z^2 + 177*x^2*y*z
    + 90*x*y^8*z^6 + 144*x*y^3*z^5 - 234*x*y^3
    + 81*y^10*z^5 - 162*y^5*z^4 + 81*z^3 := by
  simp only [H1, f1, f3, f4, ell]
  ring

/-- Expanded form of `H2`, as recorded in `witnesses.txt`. -/
theorem H2_expanded : H2 x y z =
    -80*x^6*y^2*z^3 + 170*x^5*y^4*z^2 + 80*x^4*y^6*z^6
    - 75*x^4*y^6*z + 15*x^4*y - 10*x^3*y^8*z^5
    + 32*x^3*y^3*z^4 - 25*x^2*y^10*z^4 - 98*x^2*y^5*z^3
    - 81*x^2*z^2 - 72*x*y^7*z^7 - 30*x*y^7*z^2
    + 102*x*y^2*z - 36*y^9*z^6 + 72*y^4*z^5 - 36*y^4 := by
  simp only [H2, f1, f2, f3, kappa]
  ring

/-- The first reverse identity. -/
theorem H1_eq : H1 x y z = (-24*x)*f1 x y z + ell x y z*f3 x y z + 81*f4 x y z := by
  simp only [H1]; ring

/-- The second reverse identity. -/
theorem H2_eq : H2 x y z = (-12*y)*f1 x y z + (27*x)*f2 x y z + kappa x y z*f3 x y z := by
  simp only [H2]

theorem H1_mem_P : H1 x y z ∈ P x y z :=
  mem_P_of_eq (c1 := -24*x) (c2 := 0) (c3 := ell x y z) (c4 := 81) (by simp only [H1]; ring)

theorem H2_mem_P : H2 x y z ∈ P x y z :=
  mem_P_of_eq (c1 := -12*y) (c2 := 27*x) (c3 := kappa x y z) (c4 := 0) (by simp only [H2]; ring)

/-- `Q ≤ P`. -/
theorem Q_le_P : Q x y z ≤ P x y z := by
  rw [Q, Ideal.span_le]
  rintro g (rfl | rfl)
  · exact H1_mem_P x y z
  · exact H2_mem_P x y z

/-- Certificate identity for `f1 * f1` (scale `5832`). -/
theorem cert_11 : (5832 : A) * (f1 x y z * f1 x y z) =
    (-1280*x^9*y^3*z^4 + 1600*x^8*y^5*z^3 - 500*x^7*y^7*z^2 + 512*x^6*y^4*z^5 + 800*x^5*y^6*z^4 - 1296*x^5*y*z^3 - 700*x^4*y^8*z^3 + 594*x^4*y^3*z^2 - 144*x^3*y^5*z^6 + 135*x^3*y^5*z - 243*x^3 - 558*x^2*y^7*z^5 + 1944*x*y^4*z^3 + 648*y^6*z^7) * H1 x y z
    + (-2048*x^10*y^2*z^4 + 2560*x^9*y^4*z^3 - 800*x^8*y^6*z^2 - 3328*x^7*y^3*z^5 + 6464*x^6*y^5*z^4 - 2740*x^5*y^7*z^3 - 3456*x^5*y^2*z^2 - 2304*x^4*y^4*z^6 + 2160*x^4*y^4*z + 4032*x^3*y^6*z^5 - 1296*x^3*y*z^4 - 2268*x^2*y^8*z^4 - 1134*x^2*y^3*z^3 - 1296*x*y^5*z^7 + 3159*x*y^5*z^2 - 243*x*z + 1458*y^7*z^6 - 1458*y^2) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f1 * f2` (scale `2916`). -/
theorem cert_12 : (2916 : A) * (f1 x y z * f2 x y z) =
    (-640*x^8*y^4*z^4 + 800*x^7*y^6*z^3 - 250*x^6*y^8*z^2 + 576*x^5*y^5*z^5 - 648*x^4*y^2*z^3 - 225*x^3*y^9*z^3 + 597*x^3*y^4*z^2 - 120*x^2*y^6*z - 54*x^2*y - 324*x*y^8*z^5 + 324*x*y^3*z^4 + 216*y^5*z^3) * H1 x y z
    + (-1024*x^9*y^3*z^4 + 1280*x^8*y^5*z^3 - 400*x^7*y^7*z^2 - 1152*x^6*y^4*z^5 + 2592*x^5*y^6*z^4 - 1170*x^4*y^8*z^3 - 1248*x^4*y^3*z^2 + 780*x^3*y^5*z + 108*x^3 + 648*x^2*y^7*z^5 - 648*x^2*y^2*z^4 - 729*x*y^9*z^4 + 297*x*y^4*z^3 + 486*y^6*z^2 - 486*y*z) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f1 * f3` (scale `972`). -/
theorem cert_13 : (972 : A) * (f1 x y z * f3 x y z) =
    (-80*x^6*y^2*z^2 + 50*x^5*y^4*z + 32*x^3*y^3*z^3 + 25*x^2*y^5*z^2 - 81*x^2*z + 54*x*y^2 + 36*y^4*z^4) * H1 x y z
    + (-128*x^7*y*z^2 + 80*x^6*y^3*z - 208*x^4*y^2*z^3 + 202*x^3*y^4*z^2 - 108*x^2*y - 72*x*y^3*z^4 + 81*y^5*z^3 - 81*z^2) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f1 * f4` (scale `8748`). -/
theorem cert_14 : (8748 : A) * (f1 x y z * f4 x y z) =
    (640*x^7*y^4*z^5 - 800*x^6*y^6*z^4 + 250*x^5*y^8*z^3 - 480*x^5*y^3*z^2 - 576*x^4*y^5*z^6 + 300*x^4*y^5*z + 648*x^3*y^2*z^4 + 225*x^2*y^9*z^4 - 405*x^2*y^4*z^3 + 270*x*y^6*z^2 - 432*x*y*z + 324*y^8*z^6 - 324*y^3*z^5 + 324*y^3) * H1 x y z
    + (1024*x^8*y^3*z^5 - 1280*x^7*y^5*z^4 + 400*x^6*y^7*z^3 - 768*x^6*y^2*z^2 + 1152*x^5*y^4*z^6 + 480*x^5*y^4*z - 2592*x^4*y^6*z^5 + 1170*x^3*y^8*z^4 + 432*x^2*y^5*z^2 - 108*x^2*z - 648*x*y^7*z^6 + 648*x*y^2*z^5 - 648*x*y^2 + 729*y^9*z^5 - 729*y^4*z^4) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f2 * f2` (scale `1458`). -/
theorem cert_22 : (1458 : A) * (f2 x y z * f2 x y z) =
    (-320*x^7*y^5*z^4 + 400*x^6*y^7*z^3 - 125*x^5*y^9*z^2 + 448*x^4*y^6*z^5 - 200*x^3*y^8*z^4 - 224*x^3*y^3*z^3 - 50*x^2*y^10*z^3 + 236*x^2*y^5*z^2 - 144*x*y^7*z^6 - 60*x*y^7*z - 12*x*y^2 - 72*y^9*z^5 + 144*y^4*z^4) * H1 x y z
    + (-512*x^8*y^4*z^4 + 640*x^7*y^6*z^3 - 200*x^6*y^8*z^2 - 320*x^5*y^5*z^5 + 976*x^4*y^7*z^4 + 160*x^4*y^2*z^3 - 485*x^3*y^9*z^3 - 724*x^3*y^4*z^2 + 288*x^2*y^6*z^6 + 390*x^2*y^6*z + 78*x^2*y - 180*x*y^8*z^5 - 288*x*y^3*z^4 - 162*y^10*z^4 + 324*y^5*z^3 - 162*z^2) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f2 * f3` (scale `486`). -/
theorem cert_23 : (486 : A) * (f2 x y z * f3 x y z) =
    (-40*x^5*y^3*z^2 + 25*x^4*y^5*z + 36*x^2*y^4*z^3 - 18*x*y*z + 12*y^3) * H1 x y z
    + (-64*x^6*y^2*z^2 + 40*x^5*y^4*z - 72*x^3*y^3*z^3 + 81*x^2*y^5*z^2 + 36*x^2*z - 78*x*y^2) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f2 * f4` (scale `4374`). -/
theorem cert_24 : (4374 : A) * (f2 x y z * f4 x y z) =
    (320*x^6*y^5*z^5 - 400*x^5*y^7*z^4 - 160*x^5*y^2*z^3 + 125*x^4*y^9*z^3 + 100*x^4*y^4*z^2 - 288*x^3*y^6*z^6 + 30*x^3*y + 180*x^2*y^8*z^5 + 288*x^2*y^3*z^4 - 216*x*y^5*z^3 - 162*x*z^2 + 108*y^2*z) * H1 x y z
    + (512*x^7*y^4*z^5 - 640*x^6*y^6*z^4 - 256*x^6*y*z^3 + 200*x^5*y^8*z^3 + 160*x^5*y^3*z^2 + 576*x^4*y^5*z^6 + 48*x^4 - 1008*x^3*y^7*z^5 - 576*x^3*y^2*z^4 + 405*x^2*y^9*z^4 + 1080*x^2*y^4*z^3 - 486*x*y^6*z^2 - 216*x*y*z) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f3 * f3` (scale `162`). -/
theorem cert_33 : (162 : A) * (f3 x y z * f3 x y z) =
    (-5*x^3*y + 2*y^2*z) * H1 x y z
    + (-8*x^4 - 13*x*y*z) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f3 * f4` (scale `1458`). -/
theorem cert_34 : (1458 : A) * (f3 x y z * f4 x y z) =
    (40*x^4*y^3*z^3 - 25*x^3*y^5*z^2 - 30*x^2*y^2 - 36*x*y^4*z^4 + 18*y*z^2) * H1 x y z
    + (64*x^5*y^2*z^3 - 40*x^4*y^4*z^2 - 48*x^3*y + 72*x^2*y^3*z^4 - 81*x*y^5*z^3 - 36*x*z^2) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

/-- Certificate identity for `f4 * f4` (scale `13122`). -/
theorem cert_44 : (13122 : A) * (f4 x y z * f4 x y z) =
    (-320*x^5*y^5*z^6 + 400*x^4*y^7*z^5 + 160*x^4*y^2*z^4 - 125*x^3*y^9*z^4 + 140*x^3*y^4*z^3 + 288*x^2*y^6*z^7 - 150*x^2*y^6*z^2 - 30*x^2*y*z - 180*x*y^8*z^6 - 288*x*y^3*z^5 - 180*x*y^3 + 162*z^3) * H1 x y z
    + (-512*x^6*y^4*z^6 + 640*x^5*y^6*z^5 + 256*x^5*y*z^4 - 200*x^4*y^8*z^4 + 224*x^4*y^3*z^3 - 576*x^3*y^5*z^7 - 240*x^3*y^5*z^2 - 48*x^3*z + 1008*x^2*y^7*z^6 + 576*x^2*y^2*z^5 - 288*x^2*y^2 - 405*x*y^9*z^5 - 648*x*y^4*z^4) * H2 x y z := by
  simp only [f1, f2, f3, f4, H1, H2, ell, kappa]
  ring

variable [Algebra ℚ A]

theorem f1f1_mem_Q : f1 x y z * f1 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 5832) (by norm_num) ?_
  rw [show (((5832 : ℕ)) : A) = (5832 : A) by norm_num, cert_11]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f1f2_mem_Q : f1 x y z * f2 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 2916) (by norm_num) ?_
  rw [show (((2916 : ℕ)) : A) = (2916 : A) by norm_num, cert_12]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f1f3_mem_Q : f1 x y z * f3 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 972) (by norm_num) ?_
  rw [show (((972 : ℕ)) : A) = (972 : A) by norm_num, cert_13]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f1f4_mem_Q : f1 x y z * f4 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 8748) (by norm_num) ?_
  rw [show (((8748 : ℕ)) : A) = (8748 : A) by norm_num, cert_14]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f2f2_mem_Q : f2 x y z * f2 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 1458) (by norm_num) ?_
  rw [show (((1458 : ℕ)) : A) = (1458 : A) by norm_num, cert_22]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f2f3_mem_Q : f2 x y z * f3 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 486) (by norm_num) ?_
  rw [show (((486 : ℕ)) : A) = (486 : A) by norm_num, cert_23]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f2f4_mem_Q : f2 x y z * f4 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 4374) (by norm_num) ?_
  rw [show (((4374 : ℕ)) : A) = (4374 : A) by norm_num, cert_24]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f3f3_mem_Q : f3 x y z * f3 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 162) (by norm_num) ?_
  rw [show (((162 : ℕ)) : A) = (162 : A) by norm_num, cert_33]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f3f4_mem_Q : f3 x y z * f4 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 1458) (by norm_num) ?_
  rw [show (((1458 : ℕ)) : A) = (1458 : A) by norm_num, cert_34]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

theorem f4f4_mem_Q : f4 x y z * f4 x y z ∈ Q x y z := by
  refine mem_of_nsmul_mem (n := 13122) (by norm_num) ?_
  rw [show (((13122 : ℕ)) : A) = (13122 : A) by norm_num, cert_44]
  exact (Q x y z).add_mem (Ideal.mul_mem_left _ _ (H1_mem x y z))
    (Ideal.mul_mem_left _ _ (H2_mem x y z))

/-- `P ^ 2 ≤ Q`: every product of two generators lies in `Q`, by the ten
scaled identities. -/
theorem P_sq_le_Q : P x y z ^ 2 ≤ Q x y z := by
  rw [pow_two, P, Ideal.span_mul_span, Ideal.span_le]
  rintro g ⟨a, ha, b, hb, rfl⟩
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha hb
  show a * b ∈ Q x y z
  rcases ha with rfl | rfl | rfl | rfl <;> rcases hb with rfl | rfl | rfl | rfl
  all_goals first
    | exact f1f1_mem_Q x y z | exact f1f2_mem_Q x y z | exact f1f3_mem_Q x y z
    | exact f1f4_mem_Q x y z | exact f2f2_mem_Q x y z | exact f2f3_mem_Q x y z
    | exact f2f4_mem_Q x y z | exact f3f3_mem_Q x y z | exact f3f4_mem_Q x y z
    | exact f4f4_mem_Q x y z
    | (rw [mul_comm]; first
        | exact f1f2_mem_Q x y z | exact f1f3_mem_Q x y z | exact f1f4_mem_Q x y z
        | exact f2f3_mem_Q x y z | exact f2f4_mem_Q x y z | exact f3f4_mem_Q x y z)

/-- From `P^2 ≤ Q ≤ P` the two ideals have the same radical, over any
`ℚ`-algebra. -/
theorem radical_Q_eq_radical_P : (Q x y z).radical = (P x y z).radical := by
  refine le_antisymm (Ideal.radical_mono (Q_le_P x y z)) ?_
  intro a ha
  rw [Ideal.mem_radical_iff] at ha ⊢
  obtain ⟨n, hn⟩ := ha
  exact ⟨n*2, by
    rw [pow_mul]
    exact P_sq_le_Q x y z (Ideal.pow_mem_pow hn 2)⟩

end MohP3.Gen
