import MohP3.Kernel

/-!
# Moh P3: the global theorem

`P` is prime (being the kernel of a ring map to the domain `ℚ[t]`) and
`Ideal.radical Q = P`, i.e. the two explicit polynomials `H1, H2` cut out the
Moh curve set-theoretically.
-/

noncomputable section

open MvPolynomial

namespace MohP3

/-- `P` is a prime ideal: it is the kernel of a map to the integral domain
`ℚ[t]`. -/
theorem P_isPrime : P.IsPrime := kernel_rho ▸ RingHom.ker_isPrime rho

/-- In particular `P` is a radical ideal. -/
theorem P_radical : P.radical = P := P_isPrime.radical

/-- The set-theoretic complete intersection statement: the radical of the ideal
generated by the two explicit witnesses `H1, H2` is the full curve ideal `P`. -/
theorem radical_Q : Ideal.radical Q = P := by
  refine le_antisymm ?_ ?_
  · calc Q.radical ≤ P.radical := Ideal.radical_mono Q_le_P
      _ = P := P_radical
  · intro a ha
    exact ⟨2, P_sq_le_Q (Ideal.pow_mem_pow ha 2)⟩

end MohP3
